### PR TITLE
rewrite to use shared queue

### PR DESCRIPTION
**Pull request by schneefux**
I threw everything away and rewrote apigrabber from scratch.
Update scheduling is now being outsourced to vainweb or the cli tool (vainglorygame/joblib#3).

### CODE REVIEW

**Comment by schneefux** [comment]
changed the table structure too, fixes #38

**Comment by kvahuja** [comment]
not sure why but i keep getting...

```
apigrabber_1             | DEBUG:asyncio:Using selector: EpollSelector
apigrabber_1             | Traceback (most recent call last):
apigrabber_1             |   File "/apps/api/api.py", line 289, in <module>
apigrabber_1             |     loop.run_until_complete(startup())
apigrabber_1             |   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
apigrabber_1             |     return future.result()
apigrabber_1             |   File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
apigrabber_1             |     raise self._exception
apigrabber_1             |   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
apigrabber_1             |     result = coro.send(None)
apigrabber_1             |   File "/apps/api/api.py", line 285, in startup
apigrabber_1             |     await apigrabber.start()
apigrabber_1             |   File "/apps/api/api.py", line 258, in start
apigrabber_1             |     await self.request_update(region)
apigrabber_1             |   File "/apps/api/api.py", line 237, in request_update
apigrabber_1             |     """, region, self.last_fetch)
apigrabber_1             |   File "/usr/local/lib/python3.5/site-packages/asyncpg/connection.py", line 289, in fetchval
apigrabber_1             |     False, timeout)
apigrabber_1             |   File "asyncpg/protocol/protocol.pyx", line 157, in bind_execute (asyncpg/protocol/protocol.c:55559)
apigrabber_1             |   File "asyncpg/protocol/prepared_stmt.pyx", line 122, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg (asyncpg/protocol/protocol.c:51680)
apigrabber_1             |   File "asyncpg/protocol/codecs/base.pyx", line 134, in asyncpg.protocol.protocol.Codec.encode (asyncpg/protocol/protocol.c:13503)
apigrabber_1             |   File "asyncpg/protocol/codecs/base.pyx", line 86, in asyncpg.protocol.protocol.Codec.encode_scalar (asyncpg/protocol/protocol.c:12943)
apigrabber_1             |   File "asyncpg/protocol/codecs/datetime.pyx", line 156, in asyncpg.protocol.protocol.timestamptz_encode (asyncpg/protocol/protocol.c:23010)
apigrabber_1             | ValueError: astimezone() cannot be applied to a naive datetime
vaindock_apigrabber exited with code 1
```

**Comment by kvahuja** [comment]
i rebuild the container and ran the job on this branch only. error

```
apigrabber_1             | Traceback (most recent call last):
apigrabber_1             |   File "/apps/api/api.py", line 9, in <module>
apigrabber_1             |     import crawler
apigrabber_1             |   File "/apps/api/crawler.py", line 70
apigrabber_1             |     yield res
apigrabber_1             |     ^
apigrabber_1             | SyntaxError: 'yield' inside async function
vaindock_apigrabber exited with code 1
```

i am debugging it now

**Comment by schneefux** [comment]
Ow! This seems to be a relatively new Python feature. I have 3.6 on my machine, but the Dockerfile is still at 3.5. Upgrade and it should work.

**Comment by schneefux** [comment]
vainglorygame/vaindock/pull/4

**Comment by kvahuja** [comment]
OK; that works. here is the Vindock. Vaindock has been upgraded too.

**Pull request merged**
